---
hydra:
  run:
    dir: .

sweep:
  dir: .
  subdir: .

output_dir: null

data_dir: "../../data/"
cache_dir: "./cache/"

seed: 0
wandb_offline: true

job:
  env_set:
    WANDB_START_METHOD: thread
    WANDB_DIR: ${oc.env:PROJECT_ROOT}

device: "cuda:0"

benchmark: "imagenet"
use_cache: true


imagenet_cfgs:
  in_dataset: "imagenet"
  out_datasets:
    - iNaturalist
    - SUN
    - Places
    - dtd
  model_name: "resnet50-supcon"
  arch_base: "resnet"
  model_path: "./ckpt/ImageNet_resnet50_supcon.pth"
  base_dir: "./output/ood_scores"
  num_workers: 2
  num_classes: 1000
  batch_size: 512


cifar10_cfgs:
  in_dataset: "cifar10"
  out_datasets:
    - SVHN
    - iSUN
    - dtd
    - places365
  arch_base: "resnet"
  model_name: "resnet18-supcon"
  model_path: "./ckpt/CIFAR10_resnet18_supcon.pth"
  # model_name: "resnet18"
  # model_path: "./ckpt/CIFAR10_resnet18.pth"
  base_dir: "./output/ood_scores"
  num_workers: 2
  num_classes: 10
  batch_size: 512
