hydra:
  run:
    dir: .

sweep:
  dir: .
  subdir: .

output_dir: null

data:
  dir: "../../data/"
  load_path: "dummy"

seed: 0
wandb_offline: true

job:
  env_set:
    WANDB_START_METHOD: thread
    WANDB_DIR: ${oc.env:PROJECT_ROOT}

device: "cuda:0"

training:
  batch_size: 64
  num_workers: 2
  epochs: 3
  offline: false
  test_bs: 200
  num_to_avg: 1
  run_type: "full_run"
  input_dim: 3072

validation:
  validate: false
  score: "recons"

loss:
  alpha: 0.5

optimizer:
  # learning_rate: 0.00075
  learning_rate: 1e-5

scheduler:
  step_size: 6
  gamma: 0.8

conv_autoencoder:
  num_layers: 5
  start_channel: 128
  kernel_size: 4
  stride: 2
  padding: 1
  img_size: [3, 32, 32]

relative_autoencoder:
  num_layers: 5
  start_channel: 128
  kernel_size: 4
  stride: 2
  padding: 1
  anchor_type: "random"
  transform_type: "cosine"
  img_size: [3, 32, 32]
  num_anchors: 1024
  relative_decoder:
    num_layers: 0
    hidden_dim: 1024

method_name: null

use_fully_connected: true

fc_autoencoder:
  input_dim: 3072
  hidden_dim: 16384
  bottleneck_size: 1024
  num_layers: 0
  use_residual: false
